cd file edited

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -33,8 +33,8 @@ jobs:
             cd /home/ubuntu/dockerized_quickserve
 
             echo "📄 Compose file:"
-            ls -la
-            [ -f compose.yml ] || { echo "❌ compose.yaml NOT FOUND"; exit 1; }
+            # ls -la
+            [ -f compose.yaml ] || { echo "❌ compose.yaml NOT FOUND"; exit 1; }
 
             echo "🐳 Docker:"
             docker --version
